#!/bin/sh

. scripts/conversions

echo ROOT DIRECTORY: ${ROOT}

if [ "$1" == "strip" ] ; then
    STRIP=strip
    shift
fi

try()
{
    echo $*
    $* || exit 1
}

progs()
{
    if [ "$STRIP" == "strip" ] ; then
        try strip tmp/${BINDIR}/icmake tmp/${BINDIR}/icmun \
                  tmp/${LIBDIR}/*
    fi
    try mkdir -p ${BINDIR} ${LIBDIR}

    try cp -r tmp/${BINDIR}/icmake tmp/${BINDIR}/icmun ${BINDIR}
    try cp -r tmp/${LIBDIR}/* ${LIBDIR}
}

scripts()
{
    try mkdir -p ${BINDIR}

      #                 script   install-dest. 
    try scripts/convert icmbuild $BINDIR
    try scripts/convert icmstart $BINDIR
    try chmod +x $BINDIR/icmbuild $BINDIR/icmstart
}

into()
{
    try mkdir -p $1
    try cp -r tmp/$1/* $1
}

case $1 in
    (all)
        progs
        scripts
        into ${MANDIR}
        into ${SKELDIR}
        into ${DOCDIR}
        into ${DOCDOCDIR}
        into etc/icmake
    ;;

    (progs)
        progs
    ;;

    (scripts)
        scripts
    ;;

    (man)
        into ${MANDIR}
    ;;

    (skel)
        into ${SKELDIR}
    ;;

    (doc)
        into ${DOCDIR}
    ;;

    (docdoc)
        into ${DOCDOCDIR}
    ;;

    (*)
        echo "Usage: $0 [strip] all|progs|scripts|man|skel|doc|docdoc"
        exit 1
    ;;
esac
