/* A lexical scanner generated by flex */

/* scanner skeleton version:
 * $Header: /usr/fsys/odin/a/vern/flex/RCS/flex.skel,v 2.16 90/08/03 14:09:36 vern Exp $
 */

#define ICCE_MODIFICATIONS                  /* look below for ICCE_MODIFIC */

#ifdef MSDOS
#define __STDC__
#endif

#define FLEX_SCANNER

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>

#ifdef ICCE_MODIFICATIONS
/*************************************************************************/
                                            /* ICCE: BEGIN OF MODIFICATIONS */
                                            /* (FBB, 12/06/93) */

#include <io.h>                             /*  contains fileno()'s prototype */

#define fileno  _fileno                     /* Ms C 7.00 name alterations */
#define read    _read

#else
#include <osfcn.h>
#endif                                      /* ICCE: END OF MODIFICATIONS */
/*************************************************************************/

/* use prototypes in function declarations */
#define YY_USE_PROTOS

/* the "const" storage-class-modifier is valid */
#define YY_USE_CONST

#else   /* ! __cplusplus */

#ifdef __STDC__

#ifdef __GNUC__
#include <stddef.h>
void *malloc( size_t );
void free( void* );
#else
#include <stdlib.h>
#endif  /* __GNUC__ */

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif  /* __STDC__ */
#endif  /* ! __cplusplus */


#ifdef __TURBOC__
#define YY_USE_CONST
#endif


#ifndef YY_USE_CONST
#define const
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
/* we can't get here if it's an ANSI C compiler, or a C++ compiler,
 * so it's got to be a K&R compiler, and therefore there's no standard
 * place from which to include these definitions
 */
char *malloc();
int free();
int read();
#endif


/* amount of stuff to slurp up with each read */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* returned upon end-of-file */
#define YY_END_TOK 0

/* copy whatever the last rule matched to the standard output */

/* cast to (char *) is because for 8-bit chars, yytext is (unsigned char *) */
/* this used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite()
 */
#define ECHO (void) fwrite( (char *) yytext, yyleng, 1, yyout )

/* gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#define YY_INPUT(buf,result,max_size) \
        if ( (result = read( fileno(yyin), (char *) buf, max_size )) < 0 ) \
            YY_FATAL_ERROR( "read() in flex scanner failed" );
#define YY_NULL 0

/* no semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#define yyterminate() return ( YY_NULL )

/* report a fatal error */

/* The funky do-while is used to turn this macro definition into
 * a single C statement (which needs a semi-colon terminator).
 * This avoids problems with code like:
 *
 *      if ( something_happens )
 *              YY_FATAL_ERROR( "oops, the something happened" );
 *      else
 *              everything_okay();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the YY_FATAL_ERROR() call.
 */

#define YY_FATAL_ERROR(msg) \
        do \
                { \
                (void) fputs( msg, stderr ); \
                (void) putc( '\n', stderr ); \
                exit( 1 ); \
                } \
        while ( 0 )

/* default yywrap function - always treat EOF as an EOF */
#define yywrap() 1

/* enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN
 */
#define BEGIN yy_start = 1 + 2 *

/* action number for EOF rule of a given start state */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* special action meaning "start processing a new file" */
#define YY_NEW_FILE \
        do \
                { \
                yy_init_buffer( yy_current_buffer, yyin ); \
                yy_load_buffer_state(); \
                } \
        while ( 0 )

/* default declaration of generated scanner - a define so the user can
 * easily add parameters
 */
#define YY_DECL int yylex YY_PROTO(( void ))

/* code executed at the end of each rule */
#define YY_BREAK break;

#define YY_END_OF_BUFFER_CHAR 0

#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE (YY_READ_BUF_SIZE * 2) /* size of default input buffer */
#endif

typedef struct yy_buffer_state *YY_BUFFER_STATE;

#define YY_CHAR char
/* # line 1 "lexer" */
#define INITIAL 0
/* # line 2 "lexer" */
/*
                                   L E X E R
*/

#include "iccomp.h"
#include "parser.h"

#undef  YY_INPUT
#define YY_INPUT(buf,result,max_size) result = yylex_input(buf, max_size);

#define str 1
/* # line 16 "lexer" */

/* done after the current pattern has been matched and before the
 * corresponding action - sets up yytext
 */
#define YY_DO_BEFORE_ACTION \
        yytext = yy_bp; \
    yyleng = yy_cp - yy_bp; \
        yy_hold_char = *yy_cp; \
        *yy_cp = '\0'; \
        yy_c_buf_p = yy_cp;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* return all but the first 'n' matched characters back to the input stream */
#define yyless(n) \
        do \
                { \
                /* undo effects of setting up yytext */ \
                *yy_cp = yy_hold_char; \
                yy_c_buf_p = yy_cp = yy_bp + n; \
                YY_DO_BEFORE_ACTION; /* set up yytext again */ \
                } \
        while ( 0 )

#define unput(c) yyunput( c, yytext )


struct yy_buffer_state
    {
    FILE *yy_input_file;

    YY_CHAR *yy_ch_buf;         /* input buffer */
    YY_CHAR *yy_buf_pos;        /* current position in input buffer */

    /* size of input buffer in bytes, not including room for EOB characters*/
    int yy_buf_size;

    /* number of characters read into yy_ch_buf, not including EOB characters */
    int yy_n_chars;

    int yy_eof_status;          /* whether we've seen an EOF on this buffer */
#define EOF_NOT_SEEN 0
    /* "pending" happens when the EOF has been seen but there's still
     * some text process
     */
#define EOF_PENDING 1
#define EOF_DONE 2
    };

static YY_BUFFER_STATE yy_current_buffer;

/* we provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state"
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed */
static YY_CHAR yy_hold_char;

static int yy_n_chars;          /* number of characters read into yy_ch_buf */



#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

#ifndef YY_USER_INIT
#define YY_USER_INIT
#endif

extern YY_CHAR *yytext;
extern int yyleng;
extern FILE *yyin, *yyout;

YY_CHAR *yytext;
int yyleng;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

#define YY_END_OF_BUFFER 95
typedef int yy_state_type;
static const short int yy_accept[322] =
    {   0,
        0,    0,    0,    0,   95,   93,    4,    5,   93,    7,
       93,   93,   93,   93,   93,   93,   93,   77,   93,   93,
       93,   92,   92,   92,   92,   93,   92,   92,   92,   92,
       92,   92,   92,   92,   92,   92,   92,   92,   92,   92,
       92,   92,   92,   93,    6,    1,    3,    1,   72,   62,
       70,   64,    0,   61,   57,   63,   58,   60,   59,   77,
       76,   73,   71,   74,   75,   92,   92,   82,   92,   92,
       92,   66,   92,   92,   92,   92,   92,   92,   92,   92,
       92,   92,   92,   92,   35,   92,   92,   92,   92,   92,
       92,   92,   92,   92,   92,   92,   92,   92,   92,   92,

       65,   69,    6,    2,    8,   67,   68,   78,   92,   92,
       92,   92,   92,   92,   92,   92,   92,   92,   92,   92,
       92,   92,   92,   92,   92,   92,   92,   34,   92,   92,
       37,   92,   92,   92,   92,   92,   92,   92,   92,   92,
       92,   92,   92,   92,   92,   92,   92,   92,   92,   92,
       92,   92,   92,   92,   92,   92,   92,   92,   92,   92,
       92,   92,   92,   92,   26,   92,   28,   29,   92,   32,
       92,   92,   92,   92,   92,   25,   38,   92,   92,   92,
       92,   92,   92,   92,   46,   92,   92,   92,   92,   92,
       92,   36,   92,   92,   89,   85,   92,   92,   92,   92,

       92,   92,   92,   92,   92,   92,   92,   92,   11,   12,
       92,   13,   92,   92,   92,   92,   92,   33,   92,   92,
       92,   92,   23,   92,   92,   55,   40,   92,   92,   92,
       92,   92,   92,   92,   92,   92,   92,   92,   54,   92,
       81,   92,   92,   92,   92,   92,   92,   92,   92,   92,
       92,   92,   92,   92,   92,   92,   92,   31,   92,   92,
       92,   92,   24,   92,   41,   42,   43,   44,   47,   48,
       49,   51,   50,   52,   53,   92,   92,   79,   92,   91,
       83,   80,   86,   88,   92,    9,   10,   92,   15,   14,
       27,   30,   19,   92,   21,   92,   92,   92,   56,   87,

       92,   90,   92,   92,   92,   20,   22,   39,   92,   84,
       92,   92,   92,   92,   92,   17,   92,   45,   16,   18,
        0
    } ;

static const YY_CHAR yy_ec[128] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    1,    7,    8,    9,    1,
        1,   10,   11,    1,   12,    1,   13,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,    1,    1,   15,
       16,   17,    1,    1,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   29,   27,   30,   31,   32,
       27,   33,   34,   35,   36,   27,   37,   38,   27,   27,
        1,   39,    1,   40,   41,    1,   42,   43,   44,   45,

       46,   47,   48,   49,   50,   27,   51,   52,   53,   54,
       55,   56,   27,   57,   58,   59,   60,   61,   62,   63,
       64,   65,    1,   66,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[67] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    3,    1,    1,    1,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    1,    1,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    1
    } ;

static const short int yy_base[327] =
    {   0,
        0,  345,   62,   63,  350,  352,  352,  352,  333,  352,
      332,   61,    0,  331,   59,   60,  330,  331,   58,  328,
       62,    0,   57,  302,  301,  325,   24,  283,   35,   41,
       35,  293,   42,  288,  295,  290,  283,   35,  288,   47,
      278,  283,  276,   55,    0,  352,  352,    0,  352,  352,
      352,  352,  321,  352,  352,  352,  352,  352,  352,  315,
      312,  352,  352,  352,  311,    0,  303,    0,   82,   79,
      299,  352,  276,  279,  276,   68,  276,  271,   62,   68,
      273,  261,  260,  257,    0,  256,  256,  262,  250,  266,
      260,  250,  249,  242,   70,  263,  247,  254,  253,  242,

      352,  352,    0,  352,  352,  352,  352,    0,  272,  274,
      273,  262,  272,  265,  100,   66,  245,  252,  239,  242,
       70,  236,  237,  243,  244,   72,  228,    0,  236,   91,
        0,  226,  238,  237,  236,  227,  234,  219,  232,  218,
       84,  218,  216,  229,  221,  218,  242,  237,  240,  249,
      245,  246,  227,  118,  242,  230,  216,  219,  210,  208,
      210,  200,  210,  213,    0,  208,    0,  193,  193,    0,
      193,  196,   99,  200,  198,    0,    0,  195,  189,  188,
      185,  189,  185,  186,    0,  186,   78,  184,  182,  178,
      190,    0,  189,  186,    0,    0,  211,  211,  211,  205,

      207,  203,  201,  204,  207,  198,  181,  172,    0,    0,
      175,    0,  178,  169,  164,  158,  158,    0,  156,  172,
      150,  170,    0,  166,  160,    0,    0,  162,  147,  153,
      159,  157,  150,  146,  151,  144,  143,  146,    0,  152,
        0,  171,  168,  173,  174,  160,  159,  167,  169,  154,
      143,  135,  145,  140,  132,  124,  136,    0,  134,  122,
      120,  119,    0,  119,    0,    0,    0,  124,    0,    0,
        0,    0,    0,    0,    0,  117,  138,    0,  148,    0,
        0,    0,    0,    0,  140,    0,    0,  107,    0,    0,
        0,    0,    0,  115,    0,  111,  100,  108,    0,    0,

      129,    0,  114,   91,  110,    0,    0,    0,   90,    0,
       88,   82,   69,   67,   71,    0,   45,    0,    0,    0,
      352,  163,  166,   83,  169,  172
    } ;

static const short int yy_def[327] =
    {   0,
      321,    1,  322,  322,  321,  321,  321,  321,  321,  321,
      321,  321,  323,  321,  321,  321,  321,  321,  321,  321,
      321,  324,  324,  324,  324,  321,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  321,  325,  321,  321,  326,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  324,  324,  324,  324,  324,
      324,  321,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,

      321,  321,  325,  321,  321,  321,  321,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,

      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,

      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
        0,  321,  321,  321,  321,  321
    } ;

static const short int yy_nxt[419] =
    {   0,
        6,    7,    8,    9,   10,    6,   11,   12,   13,   14,
       15,   16,   17,   18,   19,   20,   21,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       23,   24,   22,   25,   22,   22,   22,   22,    6,   26,
       22,   27,   28,   29,   22,   30,   31,   32,   22,   33,
       22,   34,   35,   36,   37,   38,   39,   40,   22,   22,
       41,   42,   22,   43,   22,   44,   47,   47,   51,   55,
      101,   57,   61,   62,   56,   58,   52,   64,   65,   67,
       73,   74,   81,   76,   78,   66,   68,   77,   85,   82,
       83,   91,   79,  320,   92,   86,   94,   69,  113,  109,

       48,   48,  110,   80,  111,   95,   96,  123,  114,  119,
       97,  140,  120,  125,  157,  112,  319,  126,  163,  124,
      102,  153,  154,  233,  158,  318,  141,  317,  164,  169,
      170,  173,  155,  186,  174,  187,  156,  202,  203,  234,
      316,  220,  188,  189,  221,  315,  175,  314,  176,  303,
      204,  313,  304,  312,  222,  311,  310,  309,  308,  307,
      306,  302,  305,   46,   46,   46,   53,  301,   53,  103,
      300,  103,  104,  299,  104,  298,  297,  296,  295,  294,
      293,  292,  291,  290,  289,  288,  287,  286,  285,  284,
      283,  282,  281,  280,  279,  278,  277,  276,  275,  274,

      273,  272,  271,  270,  269,  268,  267,  266,  265,  264,
      263,  262,  261,  260,  259,  258,  257,  256,  255,  254,
      253,  252,  251,  250,  249,  248,  247,  246,  245,  244,
      243,  242,  241,  240,  239,  238,  237,  236,  235,  232,
      231,  230,  229,  228,  227,  226,  225,  224,  223,  219,
      218,  217,  216,  215,  214,  213,  212,  211,  210,  209,
      208,  207,  206,  205,  201,  200,  199,  198,  197,  196,
      195,  194,  193,  192,  191,  190,  185,  184,  183,  182,
      181,  180,  179,  178,  177,  172,  171,  168,  167,  166,
      165,  162,  161,  160,  159,  152,  151,  150,  149,  148,

      147,  146,  145,  144,  143,  142,  139,  138,  137,  136,
      135,  134,  133,  132,  131,  130,  129,  128,  127,  122,
      121,  118,  117,  116,  115,  108,  107,  106,   60,  105,
      100,   99,   98,   93,   90,   89,   88,   87,   84,   75,
       72,   71,   70,   63,   60,   59,   54,   50,   49,  321,
       45,    5,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,

      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321
    } ;

static const short int yy_chk[419] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    3,    4,   12,   15,
       44,   16,   19,   19,   15,   16,   12,   21,   21,   23,
       27,   27,   31,   29,   30,  324,   23,   29,   33,   31,
       31,   38,   30,  317,   38,   33,   40,   23,   70,   69,

        3,    4,   69,   30,   69,   40,   40,   79,   70,   76,
       40,   95,   76,   80,  116,   69,  315,   80,  121,   79,
       44,  115,  115,  187,  116,  314,   95,  313,  121,  126,
      126,  130,  115,  141,  130,  141,  115,  154,  154,  187,
      312,  173,  141,  141,  173,  311,  130,  309,  130,  288,
      154,  305,  288,  304,  173,  303,  301,  298,  297,  296,
      294,  285,  288,  322,  322,  322,  323,  279,  323,  325,
      277,  325,  326,  276,  326,  268,  264,  262,  261,  260,
      259,  257,  256,  255,  254,  253,  252,  251,  250,  249,
      248,  247,  246,  245,  244,  243,  242,  240,  238,  237,

      236,  235,  234,  233,  232,  231,  230,  229,  228,  225,
      224,  222,  221,  220,  219,  217,  216,  215,  214,  213,
      211,  208,  207,  206,  205,  204,  203,  202,  201,  200,
      199,  198,  197,  194,  193,  191,  190,  189,  188,  186,
      184,  183,  182,  181,  180,  179,  178,  175,  174,  172,
      171,  169,  168,  166,  164,  163,  162,  161,  160,  159,
      158,  157,  156,  155,  153,  152,  151,  150,  149,  148,
      147,  146,  145,  144,  143,  142,  140,  139,  138,  137,
      136,  135,  134,  133,  132,  129,  127,  125,  124,  123,
      122,  120,  119,  118,  117,  114,  113,  112,  111,  110,

      109,  100,   99,   98,   97,   96,   94,   93,   92,   91,
       90,   89,   88,   87,   86,   84,   83,   82,   81,   78,
       77,   75,   74,   73,   71,   67,   65,   61,   60,   53,
       43,   42,   41,   39,   37,   36,   35,   34,   32,   28,
       26,   25,   24,   20,   18,   17,   14,   11,    9,    5,
        2,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,

      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321
    } ;

static yy_state_type yy_last_accepting_state;
static YY_CHAR *yy_last_accepting_cpos;

/* the intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0

/* these variables are all declared out here so that section 3 code can
 * manipulate them
 */
/* points to current character in buffer */
static YY_CHAR *yy_c_buf_p = (YY_CHAR *) 0;
/* ICCE MOD : static int yy_init = 1;            whether we need to initialize */
int yy_init = 1;
static int yy_start = 0;        /* start state number */

/* flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yyunput YY_PROTO(( YY_CHAR c, YY_CHAR *buf_ptr ));
void yyrestart YY_PROTO(( FILE *input_file ));
void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));

#define yy_new_buffer yy_create_buffer

#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif

YY_DECL
    {
    register yy_state_type yy_current_state;
    register YY_CHAR *yy_cp, *yy_bp;
    register int yy_act;




    if ( yy_init )
        {
        YY_USER_INIT;

        if ( ! yy_start )
            yy_start = 1;       /* first start state */

        if ( ! yyin )
            yyin = stdin;

        if ( ! yyout )
            yyout = stdout;

        if ( yy_current_buffer )
            yy_init_buffer( yy_current_buffer, yyin );
        else
            yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

        yy_load_buffer_state();

        yy_init = 0;
        }

    while ( 1 )         /* loops until end-of-file is reached */
        {
        yy_cp = yy_c_buf_p;

        /* support of yytext */
        *yy_cp = yy_hold_char;

        /* yy_bp points to the position in yy_ch_buf of the start of the
         * current run.
         */
        yy_bp = yy_cp;

    yy_current_state = yy_start;
    if ( yy_bp[-1] == '\n' )
        ++yy_current_state;
yy_match:
    do
        {
        register YY_CHAR yy_c = yy_ec[(int)*yy_cp];
        if ( yy_accept[yy_current_state] )
        {
        yy_last_accepting_state = yy_current_state;
        yy_last_accepting_cpos = yy_cp;
        }
        while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
        {
        yy_current_state = yy_def[yy_current_state];
        if ( yy_current_state >= 322 )
            yy_c = yy_meta[(int)yy_c];
        }
        yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
        ++yy_cp;
        }
    while ( yy_current_state != 321 );
    yy_cp = yy_last_accepting_cpos;
    yy_current_state = yy_last_accepting_state;

yy_find_action:
    yy_act = yy_accept[yy_current_state];

        YY_DO_BEFORE_ACTION;
        YY_USER_ACTION;

do_action:      /* this label is used only to access EOF actions */


        switch ( yy_act )
            {
        case 0: /* must backtrack */
        /* undo the effects of YY_DO_BEFORE_ACTION */
        *yy_cp = yy_hold_char;
        yy_cp = yy_last_accepting_cpos;
        yy_current_state = yy_last_accepting_state;
        goto yy_find_action;

case 1:
/* # line 19 "lexer" */
case 2:
/* # line 19 "lexer" */
{
                            strcat(string, yytext);
                        }
    YY_BREAK
case 3:
/* # line 22 "lexer" */
{
                            BEGIN 0;
                            if (!stresc(string))
                                semantic("illegal escape sequence in string");
                            return(STRING);
                        }
    YY_BREAK
case 4:
/* # line 28 "lexer" */
;
    YY_BREAK
case 5:
/* # line 29 "lexer" */
yylineno++;
    YY_BREAK
case 6:
/* # line 30 "lexer" */
{
                            change_file(yytext + 1);
                        }
    YY_BREAK
case 7:
/* # line 33 "lexer" */
{
                            string[0] = 0; BEGIN str;
                        }
    YY_BREAK
case 8:
/* # line 36 "lexer" */
{
                            sprintf(string, "%d%c", yytext[1], 0);
                            return(NUMBER);
                        }
    YY_BREAK
case 9:
/* # line 40 "lexer" */
{
                            yylval.type = f_arg_head;
                            return(ARG_HEAD);
                        }
    YY_BREAK
case 10:
/* # line 44 "lexer" */
{
                            yylval.type = f_arg_tail;
                            return(ARG_TAIL);
                        }
    YY_BREAK
case 11:
/* # line 48 "lexer" */
{                   /* ascii_int may become ascii_str */
                            yylval.type = f_ascii_int;
                            return(ASCII);
                        }
    YY_BREAK
case 12:
/* # line 52 "lexer" */
{
                            return(BREAK);
                        }
    YY_BREAK
case 13:
/* # line 55 "lexer" */
{
                            yylval.type = f_chdir;
                            return(CHDIR);
                        }
    YY_BREAK
case 14:
/* # line 59 "lexer" */
{
                            yylval.type = f_cmd_tail;
                            return(CMD_TAIL);
                        }
    YY_BREAK
case 15:
/* # line 63 "lexer" */
{
                            yylval.type = f_cmd_head;
                            return(CMD_HEAD);
                        }
    YY_BREAK
case 16:
/* # line 67 "lexer" */
{
                            yylval.type = f_c_base;
                            return(C_BASE);
                        }
    YY_BREAK
case 17:
/* # line 71 "lexer" */
{
                            yylval.type = f_c_ext;
                            return(C_EXT);
                        }
    YY_BREAK
case 18:
/* # line 75 "lexer" */
{
                            yylval.type = f_c_path;
                            return(C_PATH);
                        }
    YY_BREAK
case 19:
/* # line 79 "lexer" */
{
                            yylval.type = f_fprintf;
                            return(FPRINTF);
                        }
    YY_BREAK
case 20:
/* # line 83 "lexer" */
{
                            yylval.type = f_g_base;
                            return(G_BASE);
                        }
    YY_BREAK
case 21:
/* # line 87 "lexer" */
{
                            yylval.type = f_g_ext;
                            return(G_EXT);
                        }
    YY_BREAK
case 22:
/* # line 91 "lexer" */
{
                            yylval.type = f_g_path;
                            return(G_PATH);
                        }
    YY_BREAK
case 23:
/* # line 95 "lexer" */
{
                            yylval.type = f_getch;
                            return(GETCH);
                        }
    YY_BREAK
case 24:
/* # line 99 "lexer" */
{
                            yylval.type = f_getpid;
                            return(GETPID);
                        }
    YY_BREAK
case 25:
/* # line 103 "lexer" */
{
                            yylval.type = f_gets;
                            return(GETS);
                        }
    YY_BREAK
case 26:
/* # line 107 "lexer" */
{
                            yylval.type = f_echo;
                            return(M_ECHO);
                        }
    YY_BREAK
case 27:
/* # line 111 "lexer" */
{
                            yylval.type = f_element;
                            return(ELEMENT);
                        }
    YY_BREAK
case 28:
/* # line 115 "lexer" */
{
                            return(ELSE);
                        }
    YY_BREAK
case 29:
/* # line 118 "lexer" */
{
                            yylval.type = f_exec;
                            return(EXEC);
                        }
    YY_BREAK
case 30:
/* # line 122 "lexer" */
{
                            yylval.type = f_execute;
                            return(EXECUTE);
                        }
    YY_BREAK
case 31:
/* # line 126 "lexer" */
{
                            yylval.type = f_exists;
                            return(EXISTS);
                        }
    YY_BREAK
case 32:
/* # line 130 "lexer" */
{
                            yylval.type = op_exit;
                            return(EXIT);
                        }
    YY_BREAK
case 33:
/* # line 134 "lexer" */
{
                            yylval.type = f_fgets;
                            return (FGETS);
                        }
    YY_BREAK
case 34:
/* # line 138 "lexer" */
{
                            return(FOR);
                        }
    YY_BREAK
case 35:
/* # line 141 "lexer" */
{
                            return(IF);
                        }
    YY_BREAK
case 36:
/* # line 144 "lexer" */
{
                            yylval.type = 0;    /* 0 == void */
                            return (VOID);
                        }
    YY_BREAK
case 37:
/* # line 148 "lexer" */
{
                            yylval.type = e_int;
                            return(INT);
                        }
    YY_BREAK
case 38:
/* # line 152 "lexer" */
{
                            yylval.type = e_list;
                            return(LIST);
                        }
    YY_BREAK
case 39:
/* # line 156 "lexer" */
{
                            yylval.type = f_makelist;
                            return(MAKELIST);
                        }
    YY_BREAK
case 40:
/* # line 160 "lexer" */
{
                            yylval.type = op_older;
                            return(OLDER);
                        }
    YY_BREAK
case 41:
/* # line 164 "lexer" */
{
                            yylval.type = f_printf;
                            return(PRINTF);
                        }
    YY_BREAK
case 42:
/* # line 168 "lexer" */
{
                            yylval.type = f_putenv;
                            return (PUTENV);
                        }
    YY_BREAK
case 43:
/* # line 172 "lexer" */
{
                            yylval.type = op_ret;
                            return(RETURN);
                        }
    YY_BREAK
case 44:
/* # line 177 "lexer" */
case 45:
/* # line 177 "lexer" */
{
                            yylval.type = f_sizeoflist;
                            return(SIZEOFLIST);
                        }
    YY_BREAK
case 46:
/* # line 181 "lexer" */
{
                            yylval.type = f_stat;
                            return (STAT);
                        }
    YY_BREAK
case 47:
/* # line 185 "lexer" */
{
                            yylval.type = e_str;
                            return(STRINGTYPE);
                        }
    YY_BREAK
case 48:
/* # line 189 "lexer" */
{
                            yylval.type = f_strlen;
                            return(STRLEN);
                        }
    YY_BREAK
case 49:
/* # line 193 "lexer" */
{
                            yylval.type = f_strlwr;
                            return(STRLWR);
                        }
    YY_BREAK
case 50:
/* # line 197 "lexer" */
{
                            yylval.type = f_strupr;
                            return(STRUPR);
                        }
    YY_BREAK
case 51:
/* # line 201 "lexer" */
{
                            yylval.type = f_fields;
                            return(FIELDS);
                        }
    YY_BREAK
case 52:
/* # line 205 "lexer" */
{
                            yylval.type = f_substr;
                            return(SUBSTR);
                        }
    YY_BREAK
case 53:
/* # line 209 "lexer" */
{
                            yylval.type = f_system;
                            return(SYSTEM);
                        }
    YY_BREAK
case 54:
/* # line 213 "lexer" */
{
                            return(WHILE);
                        }
    YY_BREAK
case 55:
/* # line 217 "lexer" */
case 56:
/* # line 217 "lexer" */
{
                            yylval.type = op_younger;
                            return(YOUNGER);
                        }
    YY_BREAK
case 57:
/* # line 221 "lexer" */
{
                            return(INC);
                        }
    YY_BREAK
case 58:
/* # line 224 "lexer" */
{
                            return(DEC);
                        }
    YY_BREAK
case 59:
/* # line 227 "lexer" */
{
                            return(DIV_IS);
                        }
    YY_BREAK
case 60:
/* # line 230 "lexer" */
{
                            return(MINUS_IS);
                        }
    YY_BREAK
case 61:
/* # line 233 "lexer" */
{
                            return(MUL_IS);
                        }
    YY_BREAK
case 62:
/* # line 236 "lexer" */
{
                            return(MOD_IS);
                        }
    YY_BREAK
case 63:
/* # line 239 "lexer" */
{
                            return(PLUS_IS);
                        }
    YY_BREAK
case 64:
/* # line 242 "lexer" */
{
                            return(AND_IS);
                        }
    YY_BREAK
case 65:
/* # line 245 "lexer" */
{
                            return(OR_IS);
                        }
    YY_BREAK
case 66:
/* # line 248 "lexer" */
{
                            return(XOR_IS);
                        }
    YY_BREAK
case 67:
/* # line 251 "lexer" */
{
                            return(SHL_IS);
                        }
    YY_BREAK
case 68:
/* # line 254 "lexer" */
{
                            return(SHR_IS);
                        }
    YY_BREAK
case 69:
/* # line 257 "lexer" */
{
                            return(OR);
                        }
    YY_BREAK
case 70:
/* # line 260 "lexer" */
{
                            return(AND);
                        }
    YY_BREAK
case 71:
/* # line 263 "lexer" */
{
                            return(EQUAL);
                        }
    YY_BREAK
case 72:
/* # line 266 "lexer" */
{
                            return(NOT_EQUAL);
                        }
    YY_BREAK
case 73:
/* # line 269 "lexer" */
{
                            return(SMALLER_EQUAL);
                        }
    YY_BREAK
case 74:
/* # line 272 "lexer" */
{
                            return(GREATER_EQUAL);
                        }
    YY_BREAK
case 75:
/* # line 275 "lexer" */
{
                            return(SHR);
                        }
    YY_BREAK
case 76:
/* # line 278 "lexer" */
{
                            return(SHL);
                        }
    YY_BREAK
case 77:
/* # line 281 "lexer" */
{
                            strcpy(string, yytext);
                            return(NUMBER);
                        }
    YY_BREAK
case 78:
/* # line 286 "lexer" */
case 79:
/* # line 286 "lexer" */
{                   /* P_CHECK: value in icm.h */
                            strcpy(string, "0");
                            return(NUMBER);
                        }
    YY_BREAK
case 80:
/* # line 291 "lexer" */
case 81:
/* # line 292 "lexer" */
case 82:
/* # line 292 "lexer" */
{
                            strcpy(string, "1");
                            return(NUMBER);
                        }
    YY_BREAK
case 83:
/* # line 297 "lexer" */
case 84:
/* # line 298 "lexer" */
case 85:
/* # line 298 "lexer" */
{                   /* O_DIR: value in icm.h */
                            strcpy(string, "2");
                            return(NUMBER);
                        }
    YY_BREAK
case 86:
/* # line 303 "lexer" */
case 87:
/* # line 303 "lexer" */
{                   /* O_SUBDIR: value in icm.h */
                            strcpy(string, "4");
                            return(NUMBER);
                        }
    YY_BREAK
case 88:
/* # line 308 "lexer" */
case 89:
/* # line 308 "lexer" */
{                   /* O_ALL: value in icm.h */
                            strcpy(string, "8");
                            return(NUMBER);
                        }
    YY_BREAK
case 90:
/* # line 312 "lexer" */
{
                            strcpy(string, "16");
                            return(NUMBER);
                        }
    YY_BREAK
case 91:
/* # line 316 "lexer" */
{
                            strcpy(string, "32");
                            return(NUMBER);
                        }
    YY_BREAK
case 92:
/* # line 320 "lexer" */
{
                            strcpy(string, yytext);
                            return(IDENTIFIER);
                        }
    YY_BREAK
case 93:
/* # line 324 "lexer" */
return(yytext[0]);
    YY_BREAK
case 94:
/* # line 325 "lexer" */
ECHO;
    YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(str):
    yyterminate();

            case YY_END_OF_BUFFER:
                {
                /* amount of text matched not including the EOB char */
                int yy_amount_of_matched_text = yy_cp - yytext - 1;

                /* undo the effects of YY_DO_BEFORE_ACTION */
                *yy_cp = yy_hold_char;

                /* note that here we test for yy_c_buf_p "<=" to the position
                 * of the first EOB in the buffer, since yy_c_buf_p will
                 * already have been incremented past the NUL character
                 * (since all states make transitions on EOB to the end-
                 * of-buffer state).  Contrast this with the test in yyinput().
                 */
                if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
                    /* this was really a NUL */
                    {
                    yy_state_type yy_next_state;

                    yy_c_buf_p = yytext + yy_amount_of_matched_text;

                    yy_current_state = yy_get_previous_state();

                    /* okay, we're now positioned to make the
                     * NUL transition.  We couldn't have
                     * yy_get_previous_state() go ahead and do it
                     * for us because it doesn't know how to deal
                     * with the possibility of jamming (and we
                     * don't want to build jamming into it because
                     * then it will run more slowly)
                     */

                    yy_next_state = yy_try_NUL_trans( yy_current_state );

                    yy_bp = yytext + YY_MORE_ADJ;

                    if ( yy_next_state )
                        {
                        /* consume the NUL */
                        yy_cp = ++yy_c_buf_p;
                        yy_current_state = yy_next_state;
                        goto yy_match;
                        }

                    else
                        {
                yy_cp = yy_last_accepting_cpos;
                yy_current_state = yy_last_accepting_state;
                        goto yy_find_action;
                        }
                    }

                else switch ( yy_get_next_buffer() )
                    {
                    case EOB_ACT_END_OF_FILE:
                        {
                        yy_did_buffer_switch_on_eof = 0;

                        if ( yywrap() )
                            {
                            /* note: because we've taken care in
                             * yy_get_next_buffer() to have set up yytext,
                             * we can now set up yy_c_buf_p so that if some
                             * total hoser (like flex itself) wants
                             * to call the scanner after we return the
                             * YY_NULL, it'll still work - another YY_NULL
                             * will get returned.
                             */
                            yy_c_buf_p = yytext + YY_MORE_ADJ;

                            yy_act = YY_STATE_EOF((yy_start - 1) / 2);
                            goto do_action;
                            }

                        else
                            {
                            if ( ! yy_did_buffer_switch_on_eof )
                                YY_NEW_FILE;
                            }
                        }
                        break;

                    case EOB_ACT_CONTINUE_SCAN:
                        yy_c_buf_p = yytext + yy_amount_of_matched_text;

                        yy_current_state = yy_get_previous_state();

                        yy_cp = yy_c_buf_p;
                        yy_bp = yytext + YY_MORE_ADJ;
                        goto yy_match;

                    case EOB_ACT_LAST_MATCH:
                        yy_c_buf_p =
                            &yy_current_buffer->yy_ch_buf[yy_n_chars];

                        yy_current_state = yy_get_previous_state();

                        yy_cp = yy_c_buf_p;
                        yy_bp = yytext + YY_MORE_ADJ;
                        goto yy_find_action;
                    }
                break;
                }

            default:
#ifdef FLEX_DEBUG
                printf( "action # %d\n", yy_act );
#endif
                YY_FATAL_ERROR(
                        "fatal flex scanner internal error--no action found" );
            }
        }
#ifdef ICCE_MODIFICATIONS
/*************************************************************************/
                                            /* ICCE: BEGIN OF MODIFICATIONS */
                                            /* (FBB, 12/06/93) */
#ifdef __cplusplus
        return (0);                         /* Ms C 7.00: returnvalue */
#endif                                      /* is required with C++ */

                                            /* ICCE: END OF MODIFICATION */
/**************************************************************************/
#endif
    }


/* yy_get_next_buffer - try to read in a new buffer
 *
 * synopsis
 *     int yy_get_next_buffer();
 *
 * returns a code representing an action
 *     EOB_ACT_LAST_MATCH -
 *     EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *     EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()

    {
    register YY_CHAR *dest = yy_current_buffer->yy_ch_buf;
    register YY_CHAR *source = yytext - 1; /* copy prev. char, too */
    register int number_to_move, i;
    int ret_val;

    if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
        YY_FATAL_ERROR(
                "fatal flex scanner internal error--end of buffer missed" );

    /* try to read more data */

    /* first move last chars to start of buffer */
    number_to_move = yy_c_buf_p - yytext;

    for ( i = 0; i < number_to_move; ++i )
        *(dest++) = *(source++);

    if ( yy_current_buffer->yy_eof_status != EOF_NOT_SEEN )
        /* don't do the read, it's not guaranteed to return an EOF,
         * just force an EOF
         */
        yy_n_chars = 0;

    else
        {
        int num_to_read = yy_current_buffer->yy_buf_size - number_to_move - 1;

        if ( num_to_read > YY_READ_BUF_SIZE )
            num_to_read = YY_READ_BUF_SIZE;

        else if ( num_to_read <= 0 )
            YY_FATAL_ERROR( "fatal error - scanner input buffer overflow" );

        /* read in more data */
        YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
                  yy_n_chars, num_to_read );
        }

    if ( yy_n_chars == 0 )
        {
        if ( number_to_move == 1 )
            {
            ret_val = EOB_ACT_END_OF_FILE;
            yy_current_buffer->yy_eof_status = EOF_DONE;
            }

        else
            {
            ret_val = EOB_ACT_LAST_MATCH;
            yy_current_buffer->yy_eof_status = EOF_PENDING;
            }
        }

    else
        ret_val = EOB_ACT_CONTINUE_SCAN;

    yy_n_chars += number_to_move;
    yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
    yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

    /* yytext begins at the second character in yy_ch_buf; the first
     * character is the one which preceded it before reading in the latest
     * buffer; it needs to be kept around in case it's a newline, so
     * yy_get_previous_state() will have with '^' rules active
     */

    yytext = &yy_current_buffer->yy_ch_buf[1];

    return ( ret_val );
    }


/* yy_get_previous_state - get the state just before the EOB char was reached
 *
 * synopsis
 *     yy_state_type yy_get_previous_state();
 */

static yy_state_type yy_get_previous_state()

    {
    register yy_state_type yy_current_state;
    register YY_CHAR *yy_cp;

    register YY_CHAR *yy_bp = yytext;

    yy_current_state = yy_start;
    if ( yy_bp[-1] == '\n' )
    ++yy_current_state;

    for ( yy_cp = yytext + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
        {
    register YY_CHAR yy_c = (*yy_cp ? yy_ec[(int)*yy_cp] : 1);
    if ( yy_accept[yy_current_state] )
        {
        yy_last_accepting_state = yy_current_state;
        yy_last_accepting_cpos = yy_cp;
        }
    while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
        {
        yy_current_state = yy_def[yy_current_state];
        if ( yy_current_state >= 322 )
        yy_c = yy_meta[(int)yy_c];
        }
    yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
        }

    return ( yy_current_state );
    }


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *     next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( register yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
register yy_state_type yy_current_state;
#endif

    {
    register int yy_is_jam;
    register YY_CHAR *yy_cp = yy_c_buf_p;

    register YY_CHAR yy_c = 1;
    if ( yy_accept[yy_current_state] )
    {
    yy_last_accepting_state = yy_current_state;
    yy_last_accepting_cpos = yy_cp;
    }
    while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
    {
    yy_current_state = yy_def[yy_current_state];
    if ( yy_current_state >= 322 )
        yy_c = yy_meta[(int)yy_c];
    }
    yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
    yy_is_jam = (yy_current_state == 321);

    return ( yy_is_jam ? 0 : yy_current_state );
    }


#ifdef YY_USE_PROTOS
static void yyunput( YY_CHAR c, register YY_CHAR *yy_bp )
#else
static void yyunput( c, yy_bp )
YY_CHAR c;
register YY_CHAR *yy_bp;
#endif

    {
    register YY_CHAR *yy_cp = yy_c_buf_p;

    /* undo effects of setting up yytext */
    *yy_cp = yy_hold_char;

    if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
        { /* need to shift things up to make room */
        register int number_to_move = yy_n_chars + 2; /* +2 for EOB chars */
        register YY_CHAR *dest =
            &yy_current_buffer->yy_ch_buf[yy_current_buffer->yy_buf_size + 2];
        register YY_CHAR *source =
            &yy_current_buffer->yy_ch_buf[number_to_move];

        while ( source > yy_current_buffer->yy_ch_buf )
            *--dest = *--source;

        yy_cp += dest - source;
        yy_bp += dest - source;
        yy_n_chars = yy_current_buffer->yy_buf_size;

        if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
            YY_FATAL_ERROR( "flex scanner push-back overflow" );
        }

    if ( yy_cp > yy_bp && yy_cp[-1] == '\n' )
        yy_cp[-2] = '\n';

    *--yy_cp = c;

    /* note: the formal parameter *must* be called "yy_bp" for this
     *       macro to now work correctly
     */
    YY_DO_BEFORE_ACTION; /* set up yytext again */
    }


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif

    {
    int c;
    YY_CHAR *yy_cp = yy_c_buf_p;

    *yy_cp = yy_hold_char;

    if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
        {
        /* yy_c_buf_p now points to the character we want to return.
         * If this occurs *before* the EOB characters, then it's a
         * valid NUL; if not, then we've hit the end of the buffer.
         */
        if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
            /* this was really a NUL */
            *yy_c_buf_p = '\0';

        else
            { /* need more input */
            yytext = yy_c_buf_p;
            ++yy_c_buf_p;

            switch ( yy_get_next_buffer() )
                {
                case EOB_ACT_END_OF_FILE:
                    {
                    if ( yywrap() )
                        {
                        yy_c_buf_p = yytext + YY_MORE_ADJ;
                        return ( EOF );
                        }

                    YY_NEW_FILE;

#ifdef __cplusplus
                    return ( yyinput() );
#else
                    return ( input() );
#endif
                    }
                    break;

                case EOB_ACT_CONTINUE_SCAN:
                    yy_c_buf_p = yytext + YY_MORE_ADJ;
                    break;

                case EOB_ACT_LAST_MATCH:
#ifdef __cplusplus
                    YY_FATAL_ERROR( "unexpected last match in yyinput()" );
#else
                    YY_FATAL_ERROR( "unexpected last match in input()" );
#endif
                }
            }
        }

    c = *yy_c_buf_p;
    yy_hold_char = *++yy_c_buf_p;

    return ( c );
    }


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif

    {
    yy_init_buffer( yy_current_buffer, input_file );
    yy_load_buffer_state();
    }


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif

    {
    if ( yy_current_buffer == new_buffer )
        return;

    if ( yy_current_buffer )
        {
        /* flush out information for old buffer */
        *yy_c_buf_p = yy_hold_char;
        yy_current_buffer->yy_buf_pos = yy_c_buf_p;
        yy_current_buffer->yy_n_chars = yy_n_chars;
        }

    yy_current_buffer = new_buffer;
    yy_load_buffer_state();

    /* we don't actually know whether we did this switch during
     * EOF (yywrap()) processing, but the only time this flag
     * is looked at is after yywrap() is called, so it's safe
     * to go ahead and always set it.
     */
    yy_did_buffer_switch_on_eof = 1;
    }


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif

    {
    yy_n_chars = yy_current_buffer->yy_n_chars;
    yytext = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
    yyin = yy_current_buffer->yy_input_file;
    yy_hold_char = *yy_c_buf_p;
    }


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif

    {
    YY_BUFFER_STATE b;

    b = (YY_BUFFER_STATE) malloc( sizeof( struct yy_buffer_state ) );

    if ( ! b )
        YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

    b->yy_buf_size = size;

    /* yy_ch_buf has to be 2 characters longer than the size given because
     * we need to put in 2 end-of-buffer characters.
     */
    b->yy_ch_buf = (YY_CHAR *) malloc( (unsigned) (b->yy_buf_size + 2) );

    if ( ! b->yy_ch_buf )
        YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

    yy_init_buffer( b, file );

    return ( b );
    }


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif

    {
    if ( b == yy_current_buffer )
        yy_current_buffer = (YY_BUFFER_STATE) 0;

    free( (char *) b->yy_ch_buf );
    free( (char *) b );
    }


#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif

    {
    b->yy_input_file = file;

    /* we put in the '\n' and start reading from [1] so that an
     * initial match-at-newline will be true.
     */

    b->yy_ch_buf[0] = '\n';
    b->yy_n_chars = 1;

    /* we always need two end-of-buffer characters.  The first causes
     * a transition to the end-of-buffer state.  The second causes
     * a jam in that state.
     */
    b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;
    b->yy_ch_buf[2] = YY_END_OF_BUFFER_CHAR;

    b->yy_buf_pos = &b->yy_ch_buf[1];

    b->yy_eof_status = EOF_NOT_SEEN;
    }
/* # line 325 "lexer" */
