#!/bin/bash

. ../bootstrap/functions
. ../bootstrap/flags

echo Creating tmp/${BINDIR}/icmbuild

echo -n .
try ${CC}  ${CFLAGS} -o ../tmp/${BINDIR}/icmbuild *.c ../tmp/libicrss.a \
                                                                ${LDFLAGS}
echo .








