#include "process.ih"

void writeCLASSESdep(Process *process)
{
    if (!process->options->gchDep)
        return;

    char classesDep[strlen(process->classes) + 1 + 3 + 1];
    strcat(strcpy(classesDep, process->classes), ".dep");

    FILE *out = openFile(classesDep, "w");

    fprintf(out, 
        "// Do not edit this file: it is rewritten by icmbuild\n");

    for (int idx = 0, end = process->nKey; idx != end; ++idx)
    {
        closure(process, idx);

        if (strlen(process->value[idx]))
            fprintf(out,
                    "%s %s\n", process->key[idx], process->value[idx]);
    }
}
