.TH "icmstart\&.rc" "7" "1992\-2016" "icmake\&.9\&.01\&.00\&.tar\&.gz" "icmstart resource file"

.PP 
.SH "NAME"
icmstart\&.rc \- The icmstart(1) resource file
.PP 
.SH "DESCRIPTION"

.PP 
The \fBicmstart\&.rc\fP file specifies the files that are installed by
\fBicmstart\fP(1)\&.
.PP 
By default \fBicmstart\&.rc\fP is found in \fI/etc/icmake/icmstart\&.rc\fP, but if a
file \fI$HOME/\&.icmake/icmstart\&.rc\fP is found then the latter file is used by
\fBicmstart\fP(1)\&. \fI$HOME/\&.icmake/icmstart\&.rc\fP in turn is overruled by
specifying a \fI\-c\fP option when invoking \fBicmstart\fP(1)\&.
.PP 
The default resource file contains the following specifications, preparing for
the construction of a \fBC++\fP program using \fBicmbuild\fP(1):
.nf 

    CLASSES
    P main\&.cc 
    P main\&.ih 
    P usage\&.cc
    P version\&.cc
    P ? scanner 
    P ? parser  
        
.fi 
The \fIicmstart\&.rc\fP file may contain:
.IP o 
empty lines, which are ignored;
.IP 
.IP o 
lines beginning with a hash\-character (\fI#\fP), also ignored;
.IP 
.IP o 
an optional installation mode followed by a source\-destination
specification\&. 

.PP 
.SH "INSTALLATION MODE"

.PP 
An installation mode consists of a combination of:
.IP o 
either a P (don\(cq\&t install with \fIicmstart xxx library\fP) or an L
(don\(cq\&t install with \fIicmstart xxx program\fP);
.IP 
.IP o 
a D, indicating that the source must also be installed by default,
i\&.e\&., if neither `program\(cq\& or `library\(cq\& was specified as second argument\&.
.IP 
.IP o 
a b, indicating that the
file must \fInot\fP be installed if the \fI\-b\fP (basic installation) option was
specified when calling \fIicmstart\fP\&.
.IP 
.IP o 
Following the optional P, L, D, b combination a space delimited
optional \fI?\fP may be specified\&. If specified the installation of the file or
directory must be confirmed by the user\&.

.PP 
.SH "SOURCE\-DESTINATION SPECIFICATIONS"

.PP 
The following source\-destination specifications can be used in an
\fIicmstart\&.rc\fP file:
.IP o 
\fIsource\fP
.br 
A plain name must exist in the \fIicmstart\(cq\&s\fP skeleton directory\&. It
is installed in the destination directory \fI`dest\(cq\&\fP specified when calling
\fBicmstart\fP(1)\&. Example:
.nf 

    CLASSES     
        
.fi 
\fIskeletondir/CLASSES\fP is installed as \fIdest/CLASSES\fP
.IP 
.IP o 
\fIpathspec\fP
.br 
If `pathspec\(cq\& does not begin with a slash it must exist in
\fIicmstart\(cq\&s\fP skeleton directory\&.  It is installed as `pathspec\(cq\& in the
destination directory specified when calling \fBicmstart\fP(1)\&. Example:
.nf 

    dir/file
        
.fi 
\fIskeletondir/dir/file\fP is installed as \fIdest/dir/file\fP
.IP 
.IP o 
\fI/pathspec\fP or \fI~/pathspec\fP
The \fI~\fP\-character is expanded to the user\(cq\&s home directory\&. The
pathspec\(cq\&s final element is installed in the destination directory specified
when calling \fBicmstart\fP(1)\&. Example:
.nf 

    ~/\&.icmake/file
        
.fi 
\fI$HOME/\&.icmake/file\fP is installed as \fIdest/file\fP
When the above source specifications are followed by a destination
specification \fIdestspec\fP (a file or non\-absolute directory specification)
then the source specification is installed as dest/destspec) below the
destination directory specified when calling \fBicmstart\fP(1)\&. Examples:
.nf 

    CLASSES CLASSES             # skeletondir/CLASSES is installed as 
                                #   dest/CLASSES
    dir/file dir/file           # skeletondir/dir/file is installed as
                                #   dest/dir/file
    ~/\&.icmake/file \&.icmake/file # $HOME/\&.icmake/file is installed as 
                                #   dest/\&.icmake/file
        
.fi 
Icmstart conveerts the destination specification to a full path 
specification\&. If this full path specification does not begin with \fIdest\(cq\&s\fP
full path specification an error message is displayed and \fIicmstart\fP ends\&.
.PP 
.SH "FILES"
The mentioned paths are sugestive only and may be installation dependent:
.IP o 
\fB/usr/share/icmake/icmconf\fP
Example of an \fBicmbuild\fP configuration file;
.IP o 
\fB/usr/share/icmake/CLASSES\fP
Example of an \fBicmbuild\fP \fICLASSES\fP file\&.
.IP o 
\fB/usr/share/icmake/icmstart\&.rc\fP
Default skeleton resource file\&.

.PP 
.SH "SEE ALSO"
\fBicmake\fP(1), \fBicmbuild\fP(1), \fBicmconf\fP(7), \fBicmstart\fP(1)
.PP 
.SH "BUGS"
None reported
.PP 
.SH "COPYRIGHT"
This is free software, distributed under the terms of the 
GNU General Public License (GPL)\&.
.PP 
.SH "AUTHOR"
Frank B\&. Brokken (\fBf\&.b\&.brokken@rug\&.nl\fP)\&.
.PP 
