.TH "icmstart" "1" "2006" "icmake\&.7\&.00\&.tar\&.gz" "starts icmbuild program maintenance"

.PP 
.SH "NAME"
icmstart \- A startup script for icmbuild program maintenance
.PP 
.SH "SYNOPSIS"
\fBicmstart\fP \fI[Options]\fP top-dir [opt-subdirs]
.PP 
.SH "DESCRIPTION"

.PP 
The \fBicmstart\fP script is a generic script that can be used to start program
maintenance using \fBicmake\fP(1) and \fBicmbuild\fP(1)\&. \fBIcmstart\fP will create an
initial directory, install the files \fICLASSES\fP and \fIicmconf\fP and
optionally subdirectories below the initial directory\&. Additional directories
may be specified following \fItop-dir\fP as \fIopt-subdirs\fP\&. These additional
directories are created as sub-directories of the \fItop-level\fP directory and
are assumed to be (class) subdirectories\&. Their names are added to the file
\fICLASSES\fP\&. Furthermore, skeleton files for the main directory and
subdirectories, by default listed in the file \fI/etc/icmake/skel\fP, may be
installed in the created directories\&.
.PP 
After Changing to the top-level directory as created by \fBicmstart\fP the \fBicmbuild\fP
script can be called for program maintenance\&.
.PP 
.SH "OPTIONS"

.PP 
\fBIcmstart\fP may be called with the following options, which (f specified) must
be the first arguments to \fBicmstart\fP:
.IP o 
\fI-f\fP
.br 
do not install skeleton files\&. By default skeleton files are installed
from either the default skeleton directory or an alternative directory
specified with the \fI-s\fP option (see below)\&.
.IP o 
\fI-s path\fP
.br 
path to the directory containing skeleton files\&.  By
default this is \fI/etc/icmake\fP\&. The skeleton directory must contain a
file \fIskel\fP that may consist of comment (empty lines and lines
beginning with the hash-mark (\fI#\fP)), and should otherwise contain
relative path names of skeleton files to be installed\&. A skeleton file
is only installed if \fBicmstart\fP has created its path below the top-level
directory\&. E\&.g\&., if a skeleton name \fIscanner/scanner\&.h\fP is
available, and the top-level directory is named \fIdemo\fP then
\fIscanner/scanner\&.h\fP is installed only if \fIdemo/scanner\fP exists\&.

.PP 
.SH "FILES"

.PP 
The mentioned paths are sugestive only and may be installation dependent:
.IP o 
\fB/usr/lib/icmake/icmconf\fP
Example of a \fBicmstart\fP configuration file;
.IP o 
\fB/usr/lib/icmake/CLASSES\fP
Example of a \fBicmstart\fP \fICLASSES\fP file\&.
.IP o 
\fB/etc/icmake/skel\fP
Frame file specifying skeleton files that may be installed\&.

.PP 
.SH "SEE ALSO"
\fBicmake\fP(1), \fBicmbuild\fP(1)
.PP 
.SH "LICENSE"
This  is free software, distributed under the terms of the `GNU General
Public License\&'\&. Copyright remains with the author\&.
.PP 
.SH "ORGANIZATION"
Computing Center, University of Groningen\&.
.PP 
.SH "BUGS"

.PP 
Please report bugs to the author:
.PP 
.SH "AUTHOR"

.PP 
Frank B\&. Brokken (f\&.b\&.brokken@rug\&.nl)\&.
